"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: agile.msg.dds_
  IDL file: LowCmd_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import agile


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowCmd_(idl.IdlStruct, typename="agile.msg.dds_.LowCmd_"):
    mode_pr: types.uint8
    mode_machine: types.uint8
    sequences: types.uint16
    motor_cmd: types.array['westlake_sdkpy.idl.agile.msg.dds_.MotorCmd_', 32]
    crc: types.uint32


