"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: agile.msg.dds_
  IDL file: BmsState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import agile


@dataclass
@annotate.final
@annotate.autoid("sequential")
class BmsState_(idl.IdlStruct, typename="agile.msg.dds_.BmsState_"):
    version: types.array[types.uint8, 3]
    error_status: types.uint8
    voltage: types.float32
    soc: types.float32
    electricity: types.float32
    elapsed_seconds: types.float32
    bat_temperature_0: types.int32
    bat_temperature_1: types.int32
    soh: types.float32


