/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RealsenseMsg.h
  Source: /home/alan/Desktop/deploy/realsense_test/msg/RealsenseMsg.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_REALSENSEMSG_H
#define DDSC_REALSENSEMSG_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_UINT8_DEFINED
#define DDS_SEQUENCE_UINT8_DEFINED
typedef struct dds_sequence_uint8
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_uint8;

#define dds_sequence_uint8__alloc() \
((dds_sequence_uint8*) dds_alloc (sizeof (dds_sequence_uint8)));

#define dds_sequence_uint8_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_UINT8_DEFINED */

typedef struct RealsenseMsg
{
  uint32_t width;
  uint32_t height;
  uint64_t timestamp;
  char * color_encoding;
  dds_sequence_uint8 color_frame;
} RealsenseMsg;

extern const dds_topic_descriptor_t RealsenseMsg_desc;

#define RealsenseMsg__alloc() \
((RealsenseMsg*) dds_alloc (sizeof (RealsenseMsg)));

#define RealsenseMsg_free(d,o) \
dds_sample_free ((d), &RealsenseMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_REALSENSEMSG_H */
