"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: agile.msg.dds_
  IDL file: IMUState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import agile


@dataclass
@annotate.final
@annotate.autoid("sequential")
class IMUState_(idl.IdlStruct, typename="agile.msg.dds_.IMUState_"):
    accelerometer: types.array[types.float32, 3]
    gyroscope: types.array[types.float32, 3]
    quaternion: types.array[types.float32, 4]
    rpy: types.array[types.float32, 3]
    temperature: types.float32
    timestamp: types.uint64


