"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: agile.msg.dds_
  IDL file: LowState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import agile


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowState_(idl.IdlStruct, typename="agile.msg.dds_.LowState_"):
    mode_pr: types.uint8
    mode_machine: types.uint8
    sequences: types.uint16
    motor_state: types.array['westlake_sdkpy.idl.agile.msg.dds_.MotorState_', 32]
    imu_state: 'westlake_sdkpy.idl.agile.msg.dds_.IMUState_'
    wireless_remote: types.array[types.uint8, 40]
    crc: types.uint32


