"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: agile.msg.dds_
  IDL file: MotorState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import agile


@dataclass
@annotate.final
@annotate.autoid("sequential")
class MotorState_(idl.IdlStruct, typename="agile.msg.dds_.MotorState_"):
    mode: types.uint8
    err_code: types.uint8
    resv: types.array[types.uint8, 2]
    q: types.float32
    dq: types.float32
    tau_est: types.float32
    temperature: types.int32


